name: Generate Lambda List File

on:
  pull_request:
    branches:
      - main

jobs:
  generate-lambda-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Artifact Name
        id: artifact-name
        run: echo "ARTIFACT_NAME=artifact-PR${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Detect and list modified functions
        run: |
          git fetch origin main
          changed_dirs=$(git diff --name-only origin/main HEAD | grep '^lambdas/' | awk -F'/' '{print $2}' | uniq)
          echo "$changed_dirs" > modified-lambdas.txt
          cat modified-lambdas.txt

      - name: Upload lambda list as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}
