name: Build and Upload Artifact

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps for your build process here
      # - name: Build Project
      #   run: ...

      - name: Create Artifact Name
        id: artifact-name
        run: echo "ARTIFACT_NAME=artifact-PR${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Build Artifact
        run: |
          # Replace this with your build commands
          # For example, zip your project files
          mkdir artifact
          echo "Sample artifact for PR ${{ github.event.pull_request.number }}" > artifact/info.txt
          zip -r ${{ env.ARTIFACT_NAME }}.zip artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.zip
