name: Deploy Lambda Functions

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.x"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-1

      - name: Detect modified functions
        run: |
          - name: Detect modified functions
          run: |
            git fetch origin main
            changed_dirs=$(git diff --name-only origin/main HEAD | grep '^lambdas/' | awk -F'/' '{print $2}' | uniq | tr '\n' ' ')
            echo "changed_dirs=$changed_dirs" >> $GITHUB_ENV

      - name: Build and Zip Files
        run: |
          if [ -z ${{ env.changed_dirs}} ]; then
            echo "No changed lambda directories detected. Skipping build and zip."
            exit 0
          fi

          for lambda_dir in ${{ env.changed_dirs}}
            echo "Building and zipping $lambda_dir"
            GOOS=linux GOARCH=amd64 go build -o ./lambdas/$lambda_dir/bootstrap ./lambdas/$lambda_dir
            zip -j ./lambdas/$lambda_dir/$lambda_dir.zip ./lambdas/$lambda_dir/bootstrap
          done

      - name: Deploy Lambda function(s)
        if: ${{ env.changed_dirs}} != ''
        run: |
          for lambda_dir in ${{ env.changed_dirs}}
            echo "Deploying $lambda_dir"
            aws lambda update-function-code --function-name $lambda_dir --zip-file fileb://lambdas/$lambda_dir/$lambda_dir.zip
          done
