name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.x"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Detect modified or new Lambda functions
        id: detect_changes
        run: |
          changed_dirs=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' | awk -F'/' '{print $2}' | uniq)
          echo "::set-output name=changed_lambdas::${changed_dirs}"

      - name: Build and Zip Files
        run: |
          for lambda_dir in $changed_dirs
          do
            echo "Building and zipping $lambda_dir"
            GOOS=linux GOARCH=amd64 go build -o ./lambdas/$lambda_dir/bootstrap ./lambdas/$lambda_dir
            zip -j ./lambdas/$lambda_dir/$lambda_dir.zip ./lambdas/$lambda_dir/bootstrap
          done

      - name: Deploy changed or new Lambda functions
        if: steps.detect_changes.outputs.changed_lambdas != ''
        run: |
          for lambda_dir in ${{ steps.detect_changes.outputs.changed_lambdas }}
          do
            echo "Deploying $lambda_dir"
            aws lambda update-function-code --function-name $lambda_dir --zip-file fileb://lambdas/$lambda_dir/$lambda_dir.zip
          done
